### ISSUE TITLE
no inicia

### ISSUE THREAD

**Issue by joaquin3347** [BullyWiiPlaza/JDuel-Links-Bot#1]
java.lang.IllegalStateException: La aplicación no finalizó normalmente.
Dígale a BullyWiiPlaza si esto representa un problema.
	at p.x.k.k.k.aUX.j(or:162)
	at p.x.k.k.k.nUL.F(bv:566)
	at java.lang.Thread.run(Unknown Source)

**Comment by BullyWiiPlaza** [comment]
I see this error sometimes happening but it fixes itself, please try again later.

Veo que este error ocurre a veces, pero se arregla solo, por favor, inténtelo de nuevo más tarde.
