### ISSUE TITLE
Auto-duel in gates doesn't work after the latest patch

### ISSUE THREAD

**Issue by MrTroika** [BullyWiiPlaza/JDuel-Links-Bot#2]
As stated. I tried restarting Duel Links, restarting the bot, redownloading both, etc, no soap.

**Comment by BullyWiiPlaza** [comment]
Hi, thanks for creating an issue. The game has been updated so I need to fix most of the bot's features. Please be patient until the update(s) are done. You can stay up-to-date by following the #announcements channel in the Discord.

**Comment by MrTroika** [comment]
Alright, cool. Thanks for responding!

**Comment by JerryClinton** [comment]
Programs errored up now redownloaded definitely not working now

**Comment by BullyWiiPlaza** [comment]
> Programs errored up now redownloaded definitely not working now

Hello, can you provide more details such as exact error messages and is your problem even related to the title of this issue?
