### ISSUE TITLE
text gibberish

### ISSUE THREAD

**Issue by cs199935** [BullyWiiPlaza/JDuel-Links-Bot#3]
[文本(2022-01-22 135231).txt](https://github.com/BullyWiiPlaza/JDuel-Links-Bot/files/7917721/2022-01-22.135231.txt)

**Comment by cs199935** [comment]
> 
it's solved I didn't install java 17

**Comment by BullyWiiPlaza** [comment]
Ok, great. I recommend installing Java 17 anyway. 👍
