### ISSUE TITLE
Application update check error

### ISSUE THREAD

**Issue by calderious** [BullyWiiPlaza/JDuel-Links-Bot#4]
When trying to open the launcher, an error is received:

"An error occurred trying to check the application's update status. Refer to the Launcher.log file for further information."

Launcher.log file is blank.

**Comment by BullyWiiPlaza** [comment]
Hi, please try this launcher as well:
https://github.com/BullyWiiPlaza/JDuel-Links-Bot/releases/download/latest-release/JDuel.Links.Bot.zip

Also, you may try a newer version of the EXE launcher from here:
https://bit.ly/3vy76C9
