### ISSUE TITLE
JDuel Links Bot Activation

### ISSUE THREAD

**Issue by marcsawiris** [BullyWiiPlaza/JDuel-Links-Bot#5]
Hello sir,
Thank you so much for your helpful program,
I donated to you before but I changed my laptop so it's my new authentication code:
DD8BBB937BFCDCF72327FCA3DACDFBB583B9B29196BE6F325D9835FF
kindly activate it
Thanks in advance and have a nice day.

**Comment by BullyWiiPlaza** [comment]
Hi, please send me your old authentication code and donation details via e-mail or a Discord private message. Thank you.
